

GET http://localhost:8080/api/board/

###
GET http://localhost:8080/api/board/1

###
GET http://localhost:8080/api/board/100000

###
PUT http://localhost:8080/api/board/1
Content-Type: application/json

{
    "no": 1,
    "title": "API 테스트 수정2",
    "content": "API로 수정한 게시글",
    "writer": "user1"
}